EVENT_TEMPLATES = [
    {
        "id": "merchant_caravan",
        "name": "Merchant Caravan",
        "emoji": "🛒",
        "description": "A traveling merchant caravan arrives with extra resources for active clans.",
        "target": "global",
        "duration_minutes": 180,
        "effects": {"gold_bonus_pct": 10, "elixir_bonus_pct": 10},
        "resolution_rewards": {"gold": 500, "elixir": 500},
    },
    {
        "id": "goblin_raid",
        "name": "Goblin Raid",
        "emoji": "👺",
        "description": "Goblins are raiding nearby villages. Defeat them for bonus loot.",
        "target": "player_pool",
        "duration_minutes": 120,
        "effects": {"pve_gold_bonus_pct": 15},
        "resolution_rewards": {"gold": 750, "clan_xp": 25},
    },
    {
        "id": "ore_surge",
        "name": "Ore Surge",
        "emoji": "⛏️",
        "description": "A temporary ore vein opens under clan territory.",
        "target": "territory",
        "duration_minutes": 240,
        "effects": {"ore_bonus_pct": 20},
        "resolution_rewards": {"shiny_ore": 30, "glowy_ore": 10},
    },
    {
        "id": "hero_training_day",
        "name": "Hero Training Day",
        "emoji": "⚔️",
        "description": "Heroes train faster while the event is active.",
        "target": "global",
        "duration_minutes": 180,
        "effects": {"hero_xp_bonus_pct": 20},
        "resolution_rewards": {"dark_elixir": 100},
    },
]
