# th_caps.py
# Baseline Town Hall cap table for Upgrade Advisor
# Current phase data filled from live Clash max-level references for heroes, walls, troops, and spells.
# Other categories remain intentionally empty until later phases.

TH_CAPS = {
    9: {
        "heroes": {
            "Barbarian King": 30,
            "Archer Queen": 30,
            "Minion Prince": 10,
        },
        "pets": {},
        "troops": {
            "Barbarian": 6,
            "Archer": 6,
            "Giant": 6,
            "Goblin": 7,
            "Wall Breaker": 5,
            "Balloon": 6,
            "Wizard": 6,
            "Healer": 4,
            "Dragon": 4,
            "P.E.K.K.A": 4,
            "Baby Dragon": 2,
            "Minion": 5,
            "Hog Rider": 5,
            "Valkyrie": 4,
            "Golem": 4,
            "Witch": 2,
            "Lava Hound": 2,
        },
        "spells": {
            "Lightning Spell": 6,
            "Healing Spell": 6,
            "Rage Spell": 5,
            "Poison Spell": 3,
            "Earthquake Spell": 3,
            "Jump Spell": 2,
            "Freeze Spell": 2,
            "Haste Spell": 2,
            "Skeleton Spell": 1,
        },
        "siege_machines": {},
        "offense_buildings": {},
        "defenses": {},
        "traps": {},
        "resource_buildings": {},
        "army_buildings": {},
        "core_buildings": {},
        "walls": {"count": 250, "max_level": 10},
    },
    10: {
        "heroes": {
            "Barbarian King": 40,
            "Archer Queen": 40,
            "Minion Prince": 20,
        },
        "pets": {},
        "troops": {
            "Barbarian": 7,
            "Archer": 7,
            "Giant": 7,
            "Goblin": 7,
            "Wall Breaker": 6,
            "Balloon": 6,
            "Wizard": 7,
            "Healer": 4,
            "Dragon": 5,
            "P.E.K.K.A": 6,
            "Baby Dragon": 4,
            "Miner": 3,
            "Minion": 6,
            "Hog Rider": 6,
            "Valkyrie": 5,
            "Golem": 5,
            "Witch": 3,
            "Lava Hound": 3,
            "Bowler": 2,
        },
        "spells": {
            "Lightning Spell": 7,
            "Healing Spell": 7,
            "Rage Spell": 5,
            "Poison Spell": 4,
            "Earthquake Spell": 4,
            "Jump Spell": 3,
            "Freeze Spell": 5,
            "Haste Spell": 4,
            "Skeleton Spell": 3,
            "Clone Spell": 3,
            "Bat Spell": 3,
        },
        "siege_machines": {},
        "offense_buildings": {},
        "defenses": {},
        "traps": {},
        "resource_buildings": {},
        "army_buildings": {},
        "core_buildings": {},
        "walls": {"count": 250, "max_level": 11},
    },
    11: {
        "heroes": {
            "Barbarian King": 50,
            "Archer Queen": 50,
            "Minion Prince": 30,
            "Grand Warden": 20,
        },
        "pets": {},
        "troops": {
            "Barbarian": 8,
            "Archer": 8,
            "Giant": 8,
            "Goblin": 8,
            "Wall Breaker": 7,
            "Balloon": 7,
            "Wizard": 8,
            "Healer": 5,
            "Dragon": 6,
            "P.E.K.K.A": 7,
            "Baby Dragon": 5,
            "Miner": 5,
            "Electro Dragon": 2,
            "Minion": 7,
            "Hog Rider": 7,
            "Valkyrie": 6,
            "Golem": 7,
            "Witch": 4,
            "Lava Hound": 4,
            "Bowler": 3,
            "Ice Golem": 3,
        },
        "spells": {
            "Lightning Spell": 8,
            "Healing Spell": 7,
            "Rage Spell": 5,
            "Poison Spell": 5,
            "Earthquake Spell": 5,
            "Jump Spell": 3,
            "Freeze Spell": 6,
            "Haste Spell": 5,
            "Skeleton Spell": 4,
            "Clone Spell": 5,
            "Bat Spell": 4,
        },
        "siege_machines": {},
        "offense_buildings": {},
        "defenses": {},
        "traps": {},
        "resource_buildings": {},
        "army_buildings": {},
        "core_buildings": {},
        "walls": {"count": 300, "max_level": 12},
    },
    12: {
        "heroes": {
            "Barbarian King": 65,
            "Archer Queen": 65,
            "Minion Prince": 40,
            "Grand Warden": 40,
        },
        "pets": {},
        "troops": {
            "Barbarian": 9,
            "Archer": 9,
            "Giant": 9,
            "Goblin": 8,
            "Wall Breaker": 8,
            "Balloon": 8,
            "Wizard": 9,
            "Healer": 5,
            "Dragon": 7,
            "P.E.K.K.A": 8,
            "Baby Dragon": 6,
            "Miner": 6,
            "Electro Dragon": 3,
            "Yeti": 2,
            "Minion": 8,
            "Hog Rider": 9,
            "Valkyrie": 7,
            "Golem": 9,
            "Witch": 5,
            "Lava Hound": 5,
            "Bowler": 4,
            "Ice Golem": 5,
            "Headhunter": 2,
        },
        "spells": {
            "Lightning Spell": 9,
            "Healing Spell": 7,
            "Rage Spell": 6,
            "Poison Spell": 6,
            "Earthquake Spell": 5,
            "Jump Spell": 3,
            "Freeze Spell": 7,
            "Haste Spell": 5,
            "Skeleton Spell": 6,
            "Clone Spell": 5,
            "Bat Spell": 5,
        },
        "siege_machines": {},
        "offense_buildings": {},
        "defenses": {},
        "traps": {},
        "resource_buildings": {},
        "army_buildings": {},
        "core_buildings": {},
        "walls": {"count": 300, "max_level": 13},
    },
    13: {
        "heroes": {
            "Barbarian King": 75,
            "Archer Queen": 75,
            "Minion Prince": 50,
            "Grand Warden": 50,
            "Royal Champion": 25,
        },
        "pets": {},
        "troops": {
            "Barbarian": 9,
            "Archer": 9,
            "Giant": 10,
            "Goblin": 8,
            "Wall Breaker": 9,
            "Balloon": 9,
            "Wizard": 10,
            "Healer": 6,
            "Dragon": 8,
            "P.E.K.K.A": 9,
            "Baby Dragon": 7,
            "Miner": 7,
            "Electro Dragon": 4,
            "Yeti": 3,
            "Dragon Rider": 2,
            "Minion": 9,
            "Hog Rider": 10,
            "Valkyrie": 8,
            "Golem": 10,
            "Witch": 5,
            "Lava Hound": 6,
            "Bowler": 5,
            "Ice Golem": 5,
            "Headhunter": 3,
            "Apprentice Warden": 2,
        },
        "spells": {
            "Lightning Spell": 9,
            "Healing Spell": 8,
            "Rage Spell": 6,
            "Poison Spell": 7,
            "Earthquake Spell": 5,
            "Jump Spell": 4,
            "Freeze Spell": 7,
            "Haste Spell": 5,
            "Skeleton Spell": 7,
            "Clone Spell": 6,
            "Bat Spell": 5,
        },
        "siege_machines": {},
        "offense_buildings": {},
        "defenses": {},
        "traps": {},
        "resource_buildings": {},
        "army_buildings": {},
        "core_buildings": {},
        "walls": {"count": 300, "max_level": 14},
    },
    14: {
        "heroes": {
            "Barbarian King": 85,
            "Archer Queen": 85,
            "Minion Prince": 60,
            "Grand Warden": 60,
            "Royal Champion": 30,
        },
        "pets": {},
        "troops": {
            "Barbarian": 10,
            "Archer": 10,
            "Giant": 10,
            "Goblin": 9,
            "Wall Breaker": 10,
            "Balloon": 10,
            "Wizard": 10,
            "Healer": 7,
            "Dragon": 9,
            "P.E.K.K.A": 9,
            "Baby Dragon": 8,
            "Miner": 8,
            "Electro Dragon": 5,
            "Yeti": 4,
            "Dragon Rider": 3,
            "Electro Titan": 2,
            "Minion": 10,
            "Hog Rider": 11,
            "Valkyrie": 9,
            "Golem": 11,
            "Witch": 5,
            "Lava Hound": 6,
            "Bowler": 6,
            "Ice Golem": 6,
            "Headhunter": 3,
            "Apprentice Warden": 3,
            "Druid": 2,
        },
        "spells": {
            "Lightning Spell": 9,
            "Healing Spell": 8,
            "Rage Spell": 6,
            "Poison Spell": 8,
            "Earthquake Spell": 6,
            "Jump Spell": 4,
            "Freeze Spell": 7,
            "Haste Spell": 5,
            "Skeleton Spell": 7,
            "Clone Spell": 7,
            "Bat Spell": 5,
        },
        "siege_machines": {},
        "offense_buildings": {},
        "defenses": {},
        "traps": {},
        "resource_buildings": {},
        "army_buildings": {},
        "core_buildings": {},
        "walls": {"count": 325, "max_level": 15},
    },
    15: {
        "heroes": {
            "Barbarian King": 90,
            "Archer Queen": 90,
            "Minion Prince": 70,
            "Grand Warden": 65,
            "Royal Champion": 40,
            "Dragon Duke": 10,
        },
        "pets": {},
        "troops": {
            "Barbarian": 11,
            "Archer": 11,
            "Giant": 11,
            "Goblin": 9,
            "Wall Breaker": 11,
            "Balloon": 10,
            "Wizard": 11,
            "Healer": 8,
            "Dragon": 10,
            "P.E.K.K.A": 10,
            "Baby Dragon": 9,
            "Miner": 9,
            "Electro Dragon": 6,
            "Yeti": 5,
            "Dragon Rider": 3,
            "Electro Titan": 3,
            "Root Rider": 2,
            "Minion": 11,
            "Hog Rider": 12,
            "Valkyrie": 10,
            "Golem": 12,
            "Witch": 6,
            "Lava Hound": 6,
            "Bowler": 7,
            "Ice Golem": 7,
            "Headhunter": 3,
            "Apprentice Warden": 4,
            "Druid": 3,
            "Furnace": 2,
        },
        "spells": {
            "Lightning Spell": 10,
            "Healing Spell": 9,
            "Rage Spell": 6,
            "Poison Spell": 9,
            "Earthquake Spell": 6,
            "Jump Spell": 5,
            "Freeze Spell": 7,
            "Haste Spell": 5,
            "Skeleton Spell": 8,
            "Clone Spell": 8,
            "Bat Spell": 6,
        },
        "siege_machines": {},
        "offense_buildings": {},
        "defenses": {},
        "traps": {},
        "resource_buildings": {},
        "army_buildings": {},
        "core_buildings": {},
        "walls": {"count": 325, "max_level": 16},
    },
    16: {
        "heroes": {
            "Barbarian King": 95,
            "Archer Queen": 95,
            "Minion Prince": 80,
            "Grand Warden": 70,
            "Royal Champion": 45,
            "Dragon Duke": 15,
        },
        "pets": {},
        "troops": {
            "Barbarian": 12,
            "Archer": 12,
            "Giant": 12,
            "Goblin": 9,
            "Wall Breaker": 12,
            "Balloon": 11,
            "Wizard": 12,
            "Healer": 9,
            "Dragon": 11,
            "P.E.K.K.A": 11,
            "Baby Dragon": 10,
            "Miner": 10,
            "Electro Dragon": 7,
            "Yeti": 6,
            "Dragon Rider": 4,
            "Electro Titan": 4,
            "Root Rider": 3,
            "Thrower": 2,
            "Minion": 12,
            "Hog Rider": 13,
            "Valkyrie": 11,
            "Golem": 13,
            "Witch": 7,
            "Lava Hound": 7,
            "Bowler": 8,
            "Ice Golem": 8,
            "Headhunter": 3,
            "Apprentice Warden": 4,
            "Druid": 4,
            "Furnace": 3,
        },
        "spells": {
            "Lightning Spell": 11,
            "Healing Spell": 10,
            "Rage Spell": 6,
            "Poison Spell": 10,
            "Earthquake Spell": 7,
            "Jump Spell": 5,
            "Freeze Spell": 7,
            "Haste Spell": 5,
            "Skeleton Spell": 8,
            "Clone Spell": 8,
            "Bat Spell": 6,
        },
        "siege_machines": {},
        "offense_buildings": {},
        "defenses": {},
        "traps": {},
        "resource_buildings": {},
        "army_buildings": {},
        "core_buildings": {},
        "walls": {"count": 325, "max_level": 17},
    },
    17: {
        "heroes": {
            "Barbarian King": 100,
            "Archer Queen": 100,
            "Minion Prince": 90,
            "Grand Warden": 75,
            "Royal Champion": 50,
            "Dragon Duke": 20,
        },
        "pets": {},
        "troops": {
            "Barbarian": 12,
            "Archer": 13,
            "Giant": 13,
            "Goblin": 9,
            "Wall Breaker": 13,
            "Balloon": 12,
            "Wizard": 13,
            "Healer": 10,
            "Dragon": 12,
            "P.E.K.K.A": 12,
            "Baby Dragon": 11,
            "Miner": 11,
            "Electro Dragon": 8,
            "Yeti": 7,
            "Dragon Rider": 5,
            "Electro Titan": 4,
            "Root Rider": 3,
            "Thrower": 3,
            "Meteor Golem": 2,
            "Minion": 13,
            "Hog Rider": 14,
            "Valkyrie": 11,
            "Golem": 14,
            "Witch": 7,
            "Lava Hound": 7,
            "Bowler": 9,
            "Ice Golem": 9,
            "Headhunter": 3,
            "Apprentice Warden": 4,
            "Druid": 5,
            "Furnace": 4,
        },
        "spells": {
            "Lightning Spell": 12,
            "Healing Spell": 11,
            "Rage Spell": 6,
            "Poison Spell": 11,
            "Earthquake Spell": 7,
            "Jump Spell": 5,
            "Freeze Spell": 7,
            "Haste Spell": 6,
            "Skeleton Spell": 8,
            "Clone Spell": 8,
            "Bat Spell": 7,
        },
        "siege_machines": {},
        "offense_buildings": {},
        "defenses": {},
        "traps": {},
        "resource_buildings": {},
        "army_buildings": {},
        "core_buildings": {},
        "walls": {"count": 350, "max_level": 18},
    },
    18: {
        "heroes": {
            "Barbarian King": 105,
            "Archer Queen": 105,
            "Minion Prince": 95,
            "Grand Warden": 80,
            "Royal Champion": 55,
            "Dragon Duke": 25,
        },
        "pets": {},
        "troops": {
            "Barbarian": 12,
            "Archer": 14,
            "Giant": 14,
            "Goblin": 9,
            "Wall Breaker": 14,
            "Balloon": 12,
            "Wizard": 14,
            "Healer": 11,
            "Dragon": 12,
            "P.E.K.K.A": 13,
            "Baby Dragon": 12,
            "Miner": 12,
            "Electro Dragon": 9,
            "Yeti": 7,
            "Dragon Rider": 6,
            "Electro Titan": 5,
            "Root Rider": 3,
            "Thrower": 4,
            "Meteor Golem": 3,
            "Minion": 14,
            "Hog Rider": 15,
            "Valkyrie": 11,
            "Golem": 14,
            "Witch": 8,
            "Lava Hound": 8,
            "Bowler": 10,
            "Ice Golem": 9,
            "Headhunter": 3,
            "Apprentice Warden": 4,
            "Druid": 5,
            "Furnace": 4,
        },
        "spells": {
            "Lightning Spell": 13,
            "Healing Spell": 12,
            "Rage Spell": 6,
            "Poison Spell": 12,
            "Earthquake Spell": 8,
            "Jump Spell": 5,
            "Freeze Spell": 7,
            "Haste Spell": 7,
            "Skeleton Spell": 8,
            "Clone Spell": 8,
            "Bat Spell": 8,
        },
        "siege_machines": {},
        "offense_buildings": {},
        "defenses": {},
        "traps": {},
        "resource_buildings": {},
        "army_buildings": {},
        "core_buildings": {},
        "walls": {"count": 350, "max_level": 19},
    },
}


def get_th_caps(th_level: int) -> dict:
    return TH_CAPS.get(th_level, {})


def get_category_caps(th_level: int, category: str) -> dict:
    return TH_CAPS.get(th_level, {}).get(category, {})


def get_item_cap(th_level: int, category: str, item_name: str, default=None):
    return TH_CAPS.get(th_level, {}).get(category, {}).get(item_name, default)


def normalize_cap_entry(entry):
    if isinstance(entry, dict):
        return {
            "count": entry.get("count", 1),
            "max_level": entry.get("max_level", 0),
        }
    return {
        "count": 1,
        "max_level": int(entry or 0),
    }
