# th_caps.py
# Baseline Town Hall cap table for Upgrade Advisor
# Start with TH 9-18 and fill categories in phases.

TH_CAPS = {
    9: {
        "heroes": {},
        "pets": {},
        "troops": {},
        "spells": {},
        "siege_machines": {},
        "offense_buildings": {},
        "defenses": {},
        "traps": {},
        "resource_buildings": {},
        "army_buildings": {},
        "core_buildings": {},
        "walls": {"count": 0, "max_level": 0},
    },
    10: {
        "heroes": {},
        "pets": {},
        "troops": {},
        "spells": {},
        "siege_machines": {},
        "offense_buildings": {},
        "defenses": {},
        "traps": {},
        "resource_buildings": {},
        "army_buildings": {},
        "core_buildings": {},
        "walls": {"count": 0, "max_level": 0},
    },
    11: {
        "heroes": {},
        "pets": {},
        "troops": {},
        "spells": {},
        "siege_machines": {},
        "offense_buildings": {},
        "defenses": {},
        "traps": {},
        "resource_buildings": {},
        "army_buildings": {},
        "core_buildings": {},
        "walls": {"count": 0, "max_level": 0},
    },
    12: {
        "heroes": {},
        "pets": {},
        "troops": {},
        "spells": {},
        "siege_machines": {},
        "offense_buildings": {},
        "defenses": {},
        "traps": {},
        "resource_buildings": {},
        "army_buildings": {},
        "core_buildings": {},
        "walls": {"count": 0, "max_level": 0},
    },
    13: {
        "heroes": {},
        "pets": {},
        "troops": {},
        "spells": {},
        "siege_machines": {},
        "offense_buildings": {},
        "defenses": {},
        "traps": {},
        "resource_buildings": {},
        "army_buildings": {},
        "core_buildings": {},
        "walls": {"count": 0, "max_level": 0},
    },
    14: {
        "heroes": {},
        "pets": {},
        "troops": {},
        "spells": {},
        "siege_machines": {},
        "offense_buildings": {},
        "defenses": {},
        "traps": {},
        "resource_buildings": {},
        "army_buildings": {},
        "core_buildings": {},
        "walls": {"count": 0, "max_level": 0},
    },
    15: {
        "heroes": {},
        "pets": {},
        "troops": {},
        "spells": {},
        "siege_machines": {},
        "offense_buildings": {},
        "defenses": {},
        "traps": {},
        "resource_buildings": {},
        "army_buildings": {},
        "core_buildings": {},
        "walls": {"count": 0, "max_level": 0},
    },
    16: {
        "heroes": {},
        "pets": {},
        "troops": {},
        "spells": {},
        "siege_machines": {},
        "offense_buildings": {},
        "defenses": {},
        "traps": {},
        "resource_buildings": {},
        "army_buildings": {},
        "core_buildings": {},
        "walls": {"count": 0, "max_level": 0},
    },
    17: {
        "heroes": {},
        "pets": {},
        "troops": {},
        "spells": {},
        "siege_machines": {},
        "offense_buildings": {},
        "defenses": {},
        "traps": {},
        "resource_buildings": {},
        "army_buildings": {},
        "core_buildings": {},
        "walls": {"count": 0, "max_level": 0},
    },
    18: {
        "heroes": {},
        "pets": {},
        "troops": {},
        "spells": {},
        "siege_machines": {},
        "offense_buildings": {},
        "defenses": {},
        "traps": {},
        "resource_buildings": {},
        "army_buildings": {},
        "core_buildings": {},
        "walls": {"count": 0, "max_level": 0},
    },
}