# th_caps.py
# Baseline Town Hall cap table for Upgrade Advisor
# Current phase data filled from live Clash max-level references for heroes, walls, troops, spells,
# siege machines, pets, offense/core buildings, defenses, traps, and resource/army buildings.

TH_CAPS = {
    9: {
        "heroes": {"Barbarian King": 30, "Archer Queen": 30, "Minion Prince": 10},
        "pets": {},
        "troops": {
            "Barbarian": 6,
            "Archer": 6,
            "Giant": 6,
            "Goblin": 6,
            "Wall Breaker": 5,
            "Balloon": 6,
            "Wizard": 6,
            "Healer": 4,
            "Dragon": 4,
            "P.E.K.K.A": 4,
            "Baby Dragon": 2,
            "Minion": 5,
            "Hog Rider": 5,
            "Valkyrie": 4,
            "Golem": 4,
            "Witch": 2,
            "Lava Hound": 2,
        },
        "spells": {
            "Lightning Spell": 6,
            "Healing Spell": 6,
            "Rage Spell": 5,
            "Poison Spell": 3,
            "Earthquake Spell": 3,
            "Jump Spell": 2,
            "Freeze Spell": 2,
            "Haste Spell": 2,
            "Skeleton Spell": 1,
        },
        "siege_machines": {},
        "offense_buildings": {
            "Army Camp": {"count": 4, "max_level": 7},
            "Barracks": {"count": 1, "max_level": 11},
            "Spell Factory": {"count": 1, "max_level": 4},
            "Dark Barracks": {"count": 1, "max_level": 6},
            "Dark Spell Factory": {"count": 1, "max_level": 4},
        },
        "defenses": {
            "Cannon": {"count": 5, "max_level": 11},
            "Archer Tower": {"count": 6, "max_level": 11},
            "Mortar": {"count": 4, "max_level": 7},
            "Air Defense": {"count": 4, "max_level": 7},
            "Wizard Tower": {"count": 4, "max_level": 7},
            "Air Sweeper": {"count": 2, "max_level": 5},
            "Hidden Tesla": {"count": 4, "max_level": 7},
            "Bomb Tower": {"count": 1, "max_level": 3},
            "X-Bow": {"count": 2, "max_level": 3},
        },
        "traps": {
            "Bomb": {"count": 6, "max_level": 6},
            "Spring Trap": {"count": 6, "max_level": 4},
            "Air Bomb": {"count": 4, "max_level": 4},
            "Giant Bomb": {"count": 4, "max_level": 3},
            "Seeking Air Mine": {"count": 4, "max_level": 2},
            "Skeleton Trap": {"count": 2, "max_level": 3},
        },
        "resource_buildings": {
            "Gold Mine": {"count": 7, "max_level": 12},
            "Elixir Collector": {"count": 7, "max_level": 12},
            "Gold Storage": {"count": 4, "max_level": 11},
            "Elixir Storage": {"count": 4, "max_level": 11},
            "Dark Elixir Drill": {"count": 3, "max_level": 6},
            "Dark Elixir Storage": {"count": 1, "max_level": 6},
            "Helper Hut": {"count": 1, "max_level": 1},
        },
        "army_buildings": {
            "Army Camp": {"count": 4, "max_level": 7},
            "Barracks": {"count": 1, "max_level": 11},
            "Clan Castle": {"count": 1, "max_level": 5},
            "Laboratory": {"count": 1, "max_level": 7},
            "Spell Factory": {"count": 1, "max_level": 4},
            "Hero Hall": {"count": 1, "max_level": 3},
            "Dark Barracks": {"count": 1, "max_level": 6},
            "Dark Spell Factory": {"count": 1, "max_level": 4},
            "Blacksmith": {"count": 1, "max_level": 2},
        },
        "core_buildings": {
            "Clan Castle": {"count": 1, "max_level": 5},
            "Laboratory": {"count": 1, "max_level": 7},
            "Hero Hall": {"count": 1, "max_level": 3},
            "Blacksmith": {"count": 1, "max_level": 2},
        },
        "walls": {"count": 250, "max_level": 10},
    },
    10: {
        "heroes": {"Barbarian King": 40, "Archer Queen": 40, "Minion Prince": 20},
        "pets": {},
        "troops": {
            "Barbarian": 7,
            "Archer": 7,
            "Giant": 7,
            "Goblin": 7,
            "Wall Breaker": 6,
            "Balloon": 6,
            "Wizard": 7,
            "Healer": 4,
            "Dragon": 5,
            "P.E.K.K.A": 6,
            "Baby Dragon": 4,
            "Miner": 3,
            "Minion": 6,
            "Hog Rider": 6,
            "Valkyrie": 5,
            "Golem": 5,
            "Witch": 3,
            "Lava Hound": 3,
            "Bowler": 2,
        },
        "spells": {
            "Lightning Spell": 7,
            "Healing Spell": 7,
            "Rage Spell": 5,
            "Poison Spell": 4,
            "Earthquake Spell": 4,
            "Jump Spell": 3,
            "Freeze Spell": 5,
            "Haste Spell": 4,
            "Skeleton Spell": 3,
            "Clone Spell": 3,
            "Bat Spell": 3,
        },
        "siege_machines": {},
        "offense_buildings": {
            "Army Camp": {"count": 4, "max_level": 8},
            "Barracks": {"count": 1, "max_level": 12},
            "Spell Factory": {"count": 1, "max_level": 5},
            "Dark Barracks": {"count": 1, "max_level": 7},
            "Dark Spell Factory": {"count": 1, "max_level": 5},
        },
        "defenses": {
            "Cannon": {"count": 6, "max_level": 13},
            "Archer Tower": {"count": 7, "max_level": 13},
            "Mortar": {"count": 4, "max_level": 8},
            "Air Defense": {"count": 4, "max_level": 8},
            "Wizard Tower": {"count": 4, "max_level": 9},
            "Air Sweeper": {"count": 2, "max_level": 6},
            "Hidden Tesla": {"count": 4, "max_level": 8},
            "Bomb Tower": {"count": 2, "max_level": 4},
            "X-Bow": {"count": 3, "max_level": 4},
            "Inferno Tower": {"count": 2, "max_level": 3},
        },
        "traps": {
            "Bomb": {"count": 6, "max_level": 7},
            "Spring Trap": {"count": 6, "max_level": 5},
            "Air Bomb": {"count": 5, "max_level": 4},
            "Giant Bomb": {"count": 5, "max_level": 4},
            "Seeking Air Mine": {"count": 5, "max_level": 3},
            "Skeleton Trap": {"count": 3, "max_level": 4},
        },
        "resource_buildings": {
            "Gold Mine": {"count": 7, "max_level": 13},
            "Elixir Collector": {"count": 7, "max_level": 13},
            "Gold Storage": {"count": 4, "max_level": 11},
            "Elixir Storage": {"count": 4, "max_level": 11},
            "Dark Elixir Drill": {"count": 3, "max_level": 7},
            "Dark Elixir Storage": {"count": 1, "max_level": 6},
            "Helper Hut": {"count": 1, "max_level": 1},
        },
        "army_buildings": {
            "Army Camp": {"count": 4, "max_level": 8},
            "Barracks": {"count": 1, "max_level": 12},
            "Clan Castle": {"count": 1, "max_level": 6},
            "Laboratory": {"count": 1, "max_level": 8},
            "Spell Factory": {"count": 1, "max_level": 5},
            "Hero Hall": {"count": 1, "max_level": 4},
            "Dark Barracks": {"count": 1, "max_level": 7},
            "Dark Spell Factory": {"count": 1, "max_level": 5},
            "Blacksmith": {"count": 1, "max_level": 3},
        },
        "core_buildings": {
            "Clan Castle": {"count": 1, "max_level": 6},
            "Laboratory": {"count": 1, "max_level": 8},
            "Hero Hall": {"count": 1, "max_level": 4},
            "Blacksmith": {"count": 1, "max_level": 3},
        },
        "walls": {"count": 275, "max_level": 11},
    },
    11: {
        "heroes": {
            "Barbarian King": 50,
            "Archer Queen": 50,
            "Minion Prince": 30,
            "Grand Warden": 20,
        },
        "pets": {},
        "troops": {
            "Barbarian": 8,
            "Archer": 8,
            "Giant": 8,
            "Goblin": 7,
            "Wall Breaker": 7,
            "Balloon": 7,
            "Wizard": 8,
            "Healer": 5,
            "Dragon": 6,
            "P.E.K.K.A": 7,
            "Baby Dragon": 5,
            "Miner": 5,
            "Electro Dragon": 2,
            "Minion": 7,
            "Hog Rider": 7,
            "Valkyrie": 6,
            "Golem": 7,
            "Witch": 4,
            "Lava Hound": 4,
            "Bowler": 3,
            "Ice Golem": 3,
        },
        "spells": {
            "Lightning Spell": 8,
            "Healing Spell": 7,
            "Rage Spell": 5,
            "Poison Spell": 5,
            "Earthquake Spell": 5,
            "Jump Spell": 3,
            "Freeze Spell": 6,
            "Haste Spell": 5,
            "Skeleton Spell": 4,
            "Clone Spell": 5,
            "Bat Spell": 4,
            "Invisibility Spell": 2,
        },
        "siege_machines": {},
        "offense_buildings": {
            "Army Camp": {"count": 4, "max_level": 9},
            "Barracks": {"count": 1, "max_level": 13},
            "Spell Factory": {"count": 1, "max_level": 6},
            "Dark Barracks": {"count": 1, "max_level": 8},
            "Dark Spell Factory": {"count": 1, "max_level": 5},
        },
        "defenses": {
            "Cannon": {"count": 7, "max_level": 15},
            "Archer Tower": {"count": 8, "max_level": 15},
            "Mortar": {"count": 4, "max_level": 10},
            "Air Defense": {"count": 4, "max_level": 9},
            "Wizard Tower": {"count": 5, "max_level": 10},
            "Air Sweeper": {"count": 2, "max_level": 7},
            "Hidden Tesla": {"count": 4, "max_level": 9},
            "Bomb Tower": {"count": 2, "max_level": 6},
            "X-Bow": {"count": 4, "max_level": 5},
            "Inferno Tower": {"count": 2, "max_level": 5},
            "Eagle Artillery": {"count": 1, "max_level": 2},
        },
        "traps": {
            "Bomb": {"count": 6, "max_level": 8},
            "Spring Trap": {"count": 6, "max_level": 6},
            "Air Bomb": {"count": 5, "max_level": 5},
            "Giant Bomb": {"count": 5, "max_level": 5},
            "Seeking Air Mine": {"count": 5, "max_level": 3},
            "Skeleton Trap": {"count": 3, "max_level": 4},
            "Tornado Trap": {"count": 1, "max_level": 2},
        },
        "resource_buildings": {
            "Gold Mine": {"count": 7, "max_level": 14},
            "Elixir Collector": {"count": 7, "max_level": 14},
            "Gold Storage": {"count": 4, "max_level": 12},
            "Elixir Storage": {"count": 4, "max_level": 12},
            "Dark Elixir Drill": {"count": 3, "max_level": 8},
            "Dark Elixir Storage": {"count": 1, "max_level": 6},
            "Helper Hut": {"count": 1, "max_level": 1},
        },
        "army_buildings": {
            "Army Camp": {"count": 4, "max_level": 9},
            "Barracks": {"count": 1, "max_level": 13},
            "Clan Castle": {"count": 1, "max_level": 7},
            "Laboratory": {"count": 1, "max_level": 9},
            "Spell Factory": {"count": 1, "max_level": 6},
            "Hero Hall": {"count": 1, "max_level": 5},
            "Dark Barracks": {"count": 1, "max_level": 8},
            "Dark Spell Factory": {"count": 1, "max_level": 6},
            "Blacksmith": {"count": 1, "max_level": 4},
        },
        "core_buildings": {
            "Clan Castle": {"count": 1, "max_level": 7},
            "Laboratory": {"count": 1, "max_level": 9},
            "Hero Hall": {"count": 1, "max_level": 5},
            "Blacksmith": {"count": 1, "max_level": 4},
        },
        "walls": {"count": 300, "max_level": 12},
    },
    12: {
        "heroes": {
            "Barbarian King": 65,
            "Archer Queen": 65,
            "Minion Prince": 40,
            "Grand Warden": 40,
        },
        "pets": {},
        "troops": {
            "Barbarian": 9,
            "Archer": 9,
            "Giant": 9,
            "Goblin": 8,
            "Wall Breaker": 8,
            "Balloon": 8,
            "Wizard": 9,
            "Healer": 5,
            "Dragon": 7,
            "P.E.K.K.A": 8,
            "Baby Dragon": 6,
            "Miner": 6,
            "Electro Dragon": 3,
            "Yeti": 2,
            "Minion": 8,
            "Hog Rider": 9,
            "Valkyrie": 7,
            "Golem": 9,
            "Witch": 5,
            "Lava Hound": 5,
            "Bowler": 4,
            "Ice Golem": 5,
            "Headhunter": 2,
        },
        "spells": {
            "Lightning Spell": 9,
            "Healing Spell": 7,
            "Rage Spell": 6,
            "Poison Spell": 6,
            "Earthquake Spell": 5,
            "Jump Spell": 3,
            "Freeze Spell": 7,
            "Haste Spell": 5,
            "Skeleton Spell": 6,
            "Clone Spell": 5,
            "Bat Spell": 5,
        },
        "siege_machines": {"Wall Wrecker": 3, "Battle Blimp": 3, "Stone Slammer": 3},
        "offense_buildings": {
            "Army Camp": {"count": 4, "max_level": 10},
            "Barracks": {"count": 1, "max_level": 14},
            "Spell Factory": {"count": 1, "max_level": 6},
            "Dark Barracks": {"count": 1, "max_level": 9},
            "Dark Spell Factory": {"count": 1, "max_level": 6},
            "Workshop": {"count": 1, "max_level": 3},
        },
        "defenses": {
            "Cannon": {"count": 7, "max_level": 17},
            "Archer Tower": {"count": 8, "max_level": 17},
            "Mortar": {"count": 4, "max_level": 12},
            "Air Defense": {"count": 4, "max_level": 10},
            "Wizard Tower": {"count": 5, "max_level": 11},
            "Air Sweeper": {"count": 2, "max_level": 7},
            "Hidden Tesla": {"count": 5, "max_level": 10},
            "Bomb Tower": {"count": 2, "max_level": 7},
            "X-Bow": {"count": 4, "max_level": 6},
            "Inferno Tower": {"count": 3, "max_level": 6},
            "Eagle Artillery": {"count": 1, "max_level": 3},
        },
        "traps": {
            "Bomb": {"count": 6, "max_level": 8},
            "Spring Trap": {"count": 8, "max_level": 7},
            "Air Bomb": {"count": 6, "max_level": 6},
            "Giant Bomb": {"count": 6, "max_level": 5},
            "Seeking Air Mine": {"count": 6, "max_level": 3},
            "Skeleton Trap": {"count": 3, "max_level": 4},
            "Tornado Trap": {"count": 1, "max_level": 3},
        },
        "resource_buildings": {
            "Gold Mine": {"count": 7, "max_level": 15},
            "Elixir Collector": {"count": 7, "max_level": 15},
            "Gold Storage": {"count": 4, "max_level": 13},
            "Elixir Storage": {"count": 4, "max_level": 13},
            "Dark Elixir Drill": {"count": 3, "max_level": 9},
            "Dark Elixir Storage": {"count": 1, "max_level": 7},
            "Helper Hut": {"count": 1, "max_level": 1},
        },
        "army_buildings": {
            "Army Camp": {"count": 4, "max_level": 10},
            "Barracks": {"count": 1, "max_level": 14},
            "Clan Castle": {"count": 1, "max_level": 8},
            "Laboratory": {"count": 1, "max_level": 10},
            "Spell Factory": {"count": 1, "max_level": 6},
            "Hero Hall": {"count": 1, "max_level": 6},
            "Dark Barracks": {"count": 1, "max_level": 9},
            "Dark Spell Factory": {"count": 1, "max_level": 6},
            "Blacksmith": {"count": 1, "max_level": 5},
            "Workshop": {"count": 1, "max_level": 3},
        },
        "core_buildings": {
            "Clan Castle": {"count": 1, "max_level": 8},
            "Laboratory": {"count": 1, "max_level": 10},
            "Hero Hall": {"count": 1, "max_level": 6},
            "Blacksmith": {"count": 1, "max_level": 5},
        },
        "walls": {"count": 300, "max_level": 13},
    },
    13: {
        "heroes": {
            "Barbarian King": 75,
            "Archer Queen": 75,
            "Minion Prince": 50,
            "Grand Warden": 50,
            "Royal Champion": 25,
        },
        "pets": {},
        "troops": {
            "Barbarian": 9,
            "Archer": 9,
            "Giant": 10,
            "Goblin": 8,
            "Wall Breaker": 9,
            "Balloon": 9,
            "Wizard": 10,
            "Healer": 6,
            "Dragon": 8,
            "P.E.K.K.A": 9,
            "Baby Dragon": 7,
            "Miner": 7,
            "Electro Dragon": 4,
            "Yeti": 3,
            "Dragon Rider": 2,
            "Minion": 9,
            "Hog Rider": 10,
            "Valkyrie": 8,
            "Golem": 10,
            "Witch": 5,
            "Lava Hound": 6,
            "Bowler": 5,
            "Ice Golem": 5,
            "Headhunter": 3,
            "Apprentice Warden": 2,
        },
        "spells": {
            "Lightning Spell": 9,
            "Healing Spell": 8,
            "Rage Spell": 6,
            "Poison Spell": 7,
            "Earthquake Spell": 5,
            "Jump Spell": 4,
            "Freeze Spell": 7,
            "Haste Spell": 5,
            "Skeleton Spell": 7,
            "Clone Spell": 6,
            "Bat Spell": 5,
            "Invisibility Spell": 4,
            "Overgrowth Spell": 2,
        },
        "siege_machines": {
            "Wall Wrecker": 4,
            "Battle Blimp": 4,
            "Stone Slammer": 4,
            "Siege Barracks": 4,
            "Log Launcher": 4,
        },
        "offense_buildings": {
            "Army Camp": {"count": 4, "max_level": 11},
            "Barracks": {"count": 1, "max_level": 15},
            "Spell Factory": {"count": 1, "max_level": 7},
            "Dark Barracks": {"count": 1, "max_level": 10},
            "Dark Spell Factory": {"count": 1, "max_level": 6},
            "Workshop": {"count": 1, "max_level": 5},
        },
        "defenses": {
            "Cannon": {"count": 7, "max_level": 19},
            "Archer Tower": {"count": 8, "max_level": 19},
            "Mortar": {"count": 4, "max_level": 13},
            "Air Defense": {"count": 4, "max_level": 11},
            "Wizard Tower": {"count": 5, "max_level": 13},
            "Air Sweeper": {"count": 2, "max_level": 7},
            "Hidden Tesla": {"count": 5, "max_level": 12},
            "Bomb Tower": {"count": 2, "max_level": 8},
            "X-Bow": {"count": 4, "max_level": 8},
            "Inferno Tower": {"count": 3, "max_level": 7},
            "Eagle Artillery": {"count": 1, "max_level": 4},
            "Scattershot": {"count": 2, "max_level": 2},
        },
        "traps": {
            "Bomb": {"count": 7, "max_level": 9},
            "Spring Trap": {"count": 9, "max_level": 8},
            "Air Bomb": {"count": 6, "max_level": 8},
            "Giant Bomb": {"count": 6, "max_level": 7},
            "Seeking Air Mine": {"count": 7, "max_level": 4},
            "Skeleton Trap": {"count": 3, "max_level": 4},
            "Tornado Trap": {"count": 1, "max_level": 3},
        },
        "resource_buildings": {
            "Gold Mine": {"count": 7, "max_level": 15},
            "Elixir Collector": {"count": 7, "max_level": 15},
            "Gold Storage": {"count": 4, "max_level": 14},
            "Elixir Storage": {"count": 4, "max_level": 14},
            "Dark Elixir Drill": {"count": 3, "max_level": 9},
            "Dark Elixir Storage": {"count": 1, "max_level": 8},
            "Helper Hut": {"count": 1, "max_level": 1},
        },
        "army_buildings": {
            "Army Camp": {"count": 4, "max_level": 11},
            "Barracks": {"count": 1, "max_level": 15},
            "Clan Castle": {"count": 1, "max_level": 9},
            "Laboratory": {"count": 1, "max_level": 11},
            "Spell Factory": {"count": 1, "max_level": 7},
            "Hero Hall": {"count": 1, "max_level": 7},
            "Dark Barracks": {"count": 1, "max_level": 10},
            "Dark Spell Factory": {"count": 1, "max_level": 6},
            "Blacksmith": {"count": 1, "max_level": 6},
            "Workshop": {"count": 1, "max_level": 5},
        },
        "core_buildings": {
            "Clan Castle": {"count": 1, "max_level": 9},
            "Laboratory": {"count": 1, "max_level": 11},
            "Hero Hall": {"count": 1, "max_level": 7},
            "Blacksmith": {"count": 1, "max_level": 6},
        },
        "walls": {"count": 300, "max_level": 14},
    },
    14: {
        "heroes": {
            "Barbarian King": 85,
            "Archer Queen": 85,
            "Minion Prince": 60,
            "Grand Warden": 60,
            "Royal Champion": 30,
        },
        "pets": {"L.A.S.S.I": 10, "Electro Owl": 10, "Mighty Yak": 10, "Unicorn": 10},
        "troops": {
            "Barbarian": 10,
            "Archer": 10,
            "Giant": 10,
            "Goblin": 8,
            "Wall Breaker": 10,
            "Balloon": 10,
            "Wizard": 10,
            "Healer": 7,
            "Dragon": 9,
            "P.E.K.K.A": 9,
            "Baby Dragon": 8,
            "Miner": 8,
            "Electro Dragon": 5,
            "Yeti": 4,
            "Dragon Rider": 3,
            "Electro Titan": 2,
            "Minion": 10,
            "Hog Rider": 11,
            "Valkyrie": 9,
            "Golem": 11,
            "Witch": 5,
            "Lava Hound": 6,
            "Bowler": 6,
            "Ice Golem": 6,
            "Headhunter": 3,
            "Apprentice Warden": 3,
            "Druid": 2,
        },
        "spells": {
            "Lightning Spell": 9,
            "Healing Spell": 8,
            "Rage Spell": 6,
            "Poison Spell": 8,
            "Earthquake Spell": 6,
            "Jump Spell": 4,
            "Freeze Spell": 7,
            "Haste Spell": 5,
            "Skeleton Spell": 7,
            "Clone Spell": 7,
            "Bat Spell": 5,
            "Invisibility Spell": 4,
            "Overgrowth Spell": 2,
            "Recall Spell": 3,
            "Ice Block Spell": 2,
        },
        "siege_machines": {
            "Wall Wrecker": 4,
            "Battle Blimp": 4,
            "Stone Slammer": 4,
            "Siege Barracks": 4,
            "Log Launcher": 4,
            "Flame Flinger": 4,
        },
        "offense_buildings": {
            "Army Camp": {"count": 4, "max_level": 11},
            "Barracks": {"count": 1, "max_level": 16},
            "Spell Factory": {"count": 1, "max_level": 7},
            "Dark Barracks": {"count": 1, "max_level": 11},
            "Dark Spell Factory": {"count": 1, "max_level": 7},
            "Workshop": {"count": 1, "max_level": 6},
            "Pet House": {"count": 1, "max_level": 4},
        },
        "defenses": {
            "Cannon": {"count": 7, "max_level": 20},
            "Archer Tower": {"count": 8, "max_level": 20},
            "Mortar": {"count": 4, "max_level": 14},
            "Air Defense": {"count": 4, "max_level": 12},
            "Wizard Tower": {"count": 5, "max_level": 14},
            "Air Sweeper": {"count": 2, "max_level": 7},
            "Hidden Tesla": {"count": 5, "max_level": 13},
            "Bomb Tower": {"count": 2, "max_level": 9},
            "X-Bow": {"count": 4, "max_level": 9},
            "Inferno Tower": {"count": 3, "max_level": 8},
            "Eagle Artillery": {"count": 1, "max_level": 5},
            "Scattershot": {"count": 2, "max_level": 3},
            "Builder Hut": {"count": 5, "max_level": 4},
        },
        "traps": {
            "Bomb": {"count": 8, "max_level": 10},
            "Spring Trap": {"count": 9, "max_level": 9},
            "Air Bomb": {"count": 7, "max_level": 9},
            "Giant Bomb": {"count": 7, "max_level": 8},
            "Seeking Air Mine": {"count": 8, "max_level": 4},
            "Skeleton Trap": {"count": 4, "max_level": 4},
            "Tornado Trap": {"count": 1, "max_level": 3},
        },
        "resource_buildings": {
            "Gold Mine": {"count": 7, "max_level": 16},
            "Elixir Collector": {"count": 7, "max_level": 16},
            "Gold Storage": {"count": 4, "max_level": 15},
            "Elixir Storage": {"count": 4, "max_level": 15},
            "Dark Elixir Drill": {"count": 3, "max_level": 10},
            "Dark Elixir Storage": {"count": 1, "max_level": 9},
            "Helper Hut": {"count": 1, "max_level": 1},
        },
        "army_buildings": {
            "Army Camp": {"count": 4, "max_level": 11},
            "Barracks": {"count": 1, "max_level": 16},
            "Clan Castle": {"count": 1, "max_level": 10},
            "Laboratory": {"count": 1, "max_level": 12},
            "Spell Factory": {"count": 1, "max_level": 7},
            "Hero Hall": {"count": 1, "max_level": 8},
            "Dark Barracks": {"count": 1, "max_level": 11},
            "Dark Spell Factory": {"count": 1, "max_level": 7},
            "Blacksmith": {"count": 1, "max_level": 7},
            "Workshop": {"count": 1, "max_level": 6},
            "Pet House": {"count": 1, "max_level": 4},
        },
        "core_buildings": {
            "Clan Castle": {"count": 1, "max_level": 10},
            "Laboratory": {"count": 1, "max_level": 12},
            "Hero Hall": {"count": 1, "max_level": 8},
            "Blacksmith": {"count": 1, "max_level": 7},
        },
        "walls": {"count": 325, "max_level": 15},
    },
    15: {
        "heroes": {
            "Barbarian King": 90,
            "Archer Queen": 90,
            "Minion Prince": 70,
            "Grand Warden": 65,
            "Royal Champion": 40,
            "Dragon Duke": 10,
        },
        "pets": {
            "L.A.S.S.I": 15,
            "Electro Owl": 10,
            "Mighty Yak": 15,
            "Unicorn": 10,
            "Frosty": 10,
            "Diggy": 10,
            "Poison Lizard": 10,
            "Phoenix": 10,
        },
        "troops": {
            "Barbarian": 11,
            "Archer": 11,
            "Giant": 11,
            "Goblin": 9,
            "Wall Breaker": 11,
            "Balloon": 10,
            "Wizard": 11,
            "Healer": 8,
            "Dragon": 10,
            "P.E.K.K.A": 10,
            "Baby Dragon": 9,
            "Miner": 9,
            "Electro Dragon": 6,
            "Yeti": 5,
            "Dragon Rider": 3,
            "Electro Titan": 3,
            "Root Rider": 2,
            "Minion": 11,
            "Hog Rider": 12,
            "Valkyrie": 10,
            "Golem": 12,
            "Witch": 6,
            "Lava Hound": 6,
            "Bowler": 7,
            "Ice Golem": 7,
            "Headhunter": 3,
            "Apprentice Warden": 4,
            "Druid": 3,
            "Furnace": 2,
        },
        "spells": {
            "Lightning Spell": 10,
            "Healing Spell": 9,
            "Rage Spell": 6,
            "Poison Spell": 9,
            "Earthquake Spell": 6,
            "Jump Spell": 5,
            "Freeze Spell": 7,
            "Haste Spell": 5,
            "Skeleton Spell": 8,
            "Clone Spell": 8,
            "Bat Spell": 6,
            "Invisibility Spell": 4,
            "Overgrowth Spell": 3,
            "Recall Spell": 4,
            "Ice Block Spell": 3,
        },
        "siege_machines": {
            "Wall Wrecker": 5,
            "Battle Blimp": 5,
            "Stone Slammer": 5,
            "Siege Barracks": 4,
            "Log Launcher": 4,
            "Flame Flinger": 4,
            "Battle Drill": 4,
        },
        "offense_buildings": {
            "Army Camp": {"count": 4, "max_level": 12},
            "Barracks": {"count": 1, "max_level": 17},
            "Spell Factory": {"count": 1, "max_level": 8},
            "Dark Barracks": {"count": 1, "max_level": 12},
            "Dark Spell Factory": {"count": 1, "max_level": 7},
            "Workshop": {"count": 1, "max_level": 7},
            "Pet House": {"count": 1, "max_level": 8},
        },
        "defenses": {
            "Cannon": {"count": 7, "max_level": 21},
            "Archer Tower": {"count": 8, "max_level": 21},
            "Mortar": {"count": 4, "max_level": 15},
            "Air Defense": {"count": 4, "max_level": 13},
            "Wizard Tower": {"count": 5, "max_level": 15},
            "Air Sweeper": {"count": 2, "max_level": 7},
            "Hidden Tesla": {"count": 5, "max_level": 14},
            "Bomb Tower": {"count": 2, "max_level": 10},
            "X-Bow": {"count": 4, "max_level": 10},
            "Inferno Tower": {"count": 3, "max_level": 9},
            "Eagle Artillery": {"count": 1, "max_level": 6},
            "Scattershot": {"count": 2, "max_level": 4},
            "Builder Hut": {"count": 5, "max_level": 5},
            "Monolith": {"count": 1, "max_level": 2},
            "Spell Tower": {"count": 2, "max_level": 3},
        },
        "traps": {
            "Bomb": {"count": 8, "max_level": 11},
            "Spring Trap": {"count": 9, "max_level": 10},
            "Air Bomb": {"count": 7, "max_level": 10},
            "Giant Bomb": {"count": 7, "max_level": 9},
            "Seeking Air Mine": {"count": 8, "max_level": 5},
            "Skeleton Trap": {"count": 4, "max_level": 4},
            "Tornado Trap": {"count": 1, "max_level": 3},
        },
        "resource_buildings": {
            "Gold Mine": {"count": 7, "max_level": 16},
            "Elixir Collector": {"count": 7, "max_level": 16},
            "Gold Storage": {"count": 4, "max_level": 16},
            "Elixir Storage": {"count": 4, "max_level": 16},
            "Dark Elixir Drill": {"count": 3, "max_level": 10},
            "Dark Elixir Storage": {"count": 1, "max_level": 10},
            "Helper Hut": {"count": 1, "max_level": 1},
        },
        "army_buildings": {
            "Army Camp": {"count": 4, "max_level": 12},
            "Barracks": {"count": 1, "max_level": 17},
            "Clan Castle": {"count": 1, "max_level": 11},
            "Laboratory": {"count": 1, "max_level": 13},
            "Spell Factory": {"count": 1, "max_level": 8},
            "Hero Hall": {"count": 1, "max_level": 9},
            "Dark Barracks": {"count": 1, "max_level": 12},
            "Dark Spell Factory": {"count": 1, "max_level": 7},
            "Blacksmith": {"count": 1, "max_level": 8},
            "Workshop": {"count": 1, "max_level": 7},
            "Pet House": {"count": 1, "max_level": 8},
        },
        "core_buildings": {
            "Clan Castle": {"count": 1, "max_level": 11},
            "Laboratory": {"count": 1, "max_level": 13},
            "Hero Hall": {"count": 1, "max_level": 9},
            "Blacksmith": {"count": 1, "max_level": 8},
        },
        "walls": {"count": 325, "max_level": 16},
    },
    16: {
        "heroes": {
            "Barbarian King": 95,
            "Archer Queen": 95,
            "Minion Prince": 80,
            "Grand Warden": 70,
            "Royal Champion": 45,
            "Dragon Duke": 15,
        },
        "pets": {
            "L.A.S.S.I": 15,
            "Electro Owl": 15,
            "Mighty Yak": 15,
            "Unicorn": 10,
            "Frosty": 10,
            "Diggy": 10,
            "Poison Lizard": 10,
            "Phoenix": 10,
            "Spirit Fox": 10,
            "Angry Jelly": 10,
        },
        "troops": {
            "Barbarian": 12,
            "Archer": 12,
            "Giant": 12,
            "Goblin": 9,
            "Wall Breaker": 12,
            "Balloon": 11,
            "Wizard": 12,
            "Healer": 9,
            "Dragon": 11,
            "P.E.K.K.A": 11,
            "Baby Dragon": 10,
            "Miner": 10,
            "Electro Dragon": 7,
            "Yeti": 6,
            "Dragon Rider": 4,
            "Electro Titan": 4,
            "Root Rider": 3,
            "Thrower": 2,
            "Minion": 12,
            "Hog Rider": 13,
            "Valkyrie": 11,
            "Golem": 13,
            "Witch": 7,
            "Lava Hound": 7,
            "Bowler": 8,
            "Ice Golem": 8,
            "Headhunter": 3,
            "Apprentice Warden": 4,
            "Druid": 4,
            "Furnace": 3,
        },
        "spells": {
            "Lightning Spell": 11,
            "Healing Spell": 10,
            "Rage Spell": 6,
            "Poison Spell": 10,
            "Earthquake Spell": 7,
            "Jump Spell": 5,
            "Freeze Spell": 7,
            "Haste Spell": 5,
            "Skeleton Spell": 8,
            "Clone Spell": 8,
            "Bat Spell": 6,
            "Invisibility Spell": 4,
            "Overgrowth Spell": 3,
            "Recall Spell": 4,
            "Ice Block Spell": 3,
            "Revive Spell": 3,
            "Totem Spell": 2,
        },
        "siege_machines": {
            "Wall Wrecker": 5,
            "Battle Blimp": 5,
            "Stone Slammer": 5,
            "Siege Barracks": 5,
            "Log Launcher": 5,
            "Flame Flinger": 5,
            "Battle Drill": 4,
            "Troop Launcher": 3,
        },
        "offense_buildings": {
            "Army Camp": {"count": 4, "max_level": 12},
            "Barracks": {"count": 1, "max_level": 18},
            "Spell Factory": {"count": 1, "max_level": 9},
            "Dark Barracks": {"count": 1, "max_level": 12},
            "Dark Spell Factory": {"count": 1, "max_level": 7},
            "Workshop": {"count": 1, "max_level": 8},
            "Pet House": {"count": 1, "max_level": 10},
        },
        "defenses": {
            "Cannon": {"count": 3, "max_level": 21},
            "Archer Tower": {"count": 4, "max_level": 21},
            "Mortar": {"count": 4, "max_level": 16},
            "Air Defense": {"count": 4, "max_level": 14},
            "Wizard Tower": {"count": 5, "max_level": 16},
            "Air Sweeper": {"count": 2, "max_level": 7},
            "Hidden Tesla": {"count": 5, "max_level": 15},
            "Bomb Tower": {"count": 2, "max_level": 11},
            "X-Bow": {"count": 4, "max_level": 11},
            "Inferno Tower": {"count": 3, "max_level": 10},
            "Eagle Artillery": {"count": 1, "max_level": 7},
            "Scattershot": {"count": 2, "max_level": 5},
            "Builder Hut": {"count": 5, "max_level": 6},
            "Monolith": {"count": 1, "max_level": 3},
            "Spell Tower": {"count": 2, "max_level": 3},
            "Multi-Archer Tower": {"count": 2, "max_level": 2},
            "Ricochet Cannon": {"count": 2, "max_level": 2},
        },
        "traps": {
            "Bomb": {"count": 8, "max_level": 12},
            "Spring Trap": {"count": 9, "max_level": 11},
            "Air Bomb": {"count": 7, "max_level": 11},
            "Giant Bomb": {"count": 7, "max_level": 10},
            "Seeking Air Mine": {"count": 8, "max_level": 6},
            "Skeleton Trap": {"count": 4, "max_level": 4},
            "Tornado Trap": {"count": 1, "max_level": 3},
        },
        "resource_buildings": {
            "Gold Mine": {"count": 7, "max_level": 17},
            "Elixir Collector": {"count": 7, "max_level": 17},
            "Gold Storage": {"count": 4, "max_level": 17},
            "Elixir Storage": {"count": 4, "max_level": 17},
            "Dark Elixir Drill": {"count": 3, "max_level": 11},
            "Dark Elixir Storage": {"count": 1, "max_level": 11},
            "Helper Hut": {"count": 1, "max_level": 1},
        },
        "army_buildings": {
            "Army Camp": {"count": 4, "max_level": 12},
            "Barracks": {"count": 1, "max_level": 18},
            "Clan Castle": {"count": 1, "max_level": 12},
            "Laboratory": {"count": 1, "max_level": 14},
            "Spell Factory": {"count": 1, "max_level": 9},
            "Hero Hall": {"count": 1, "max_level": 10},
            "Dark Barracks": {"count": 1, "max_level": 12},
            "Dark Spell Factory": {"count": 1, "max_level": 7},
            "Blacksmith": {"count": 1, "max_level": 9},
            "Workshop": {"count": 1, "max_level": 8},
            "Pet House": {"count": 1, "max_level": 10},
        },
        "core_buildings": {
            "Clan Castle": {"count": 1, "max_level": 12},
            "Laboratory": {"count": 1, "max_level": 14},
            "Hero Hall": {"count": 1, "max_level": 10},
            "Blacksmith": {"count": 1, "max_level": 9},
        },
        "walls": {"count": 325, "max_level": 17},
    },
    17: {
        "heroes": {
            "Barbarian King": 100,
            "Archer Queen": 100,
            "Minion Prince": 90,
            "Grand Warden": 75,
            "Royal Champion": 50,
            "Dragon Duke": 20,
        },
        "pets": {
            "L.A.S.S.I": 15,
            "Electro Owl": 15,
            "Mighty Yak": 15,
            "Unicorn": 15,
            "Frosty": 15,
            "Diggy": 10,
            "Poison Lizard": 15,
            "Phoenix": 10,
            "Spirit Fox": 10,
            "Angry Jelly": 10,
            "Sneezy": 10,
        },
        "troops": {
            "Barbarian": 12,
            "Archer": 13,
            "Giant": 13,
            "Goblin": 9,
            "Wall Breaker": 13,
            "Balloon": 12,
            "Wizard": 13,
            "Healer": 10,
            "Dragon": 12,
            "P.E.K.K.A": 12,
            "Baby Dragon": 11,
            "Miner": 11,
            "Electro Dragon": 8,
            "Yeti": 7,
            "Dragon Rider": 5,
            "Electro Titan": 4,
            "Root Rider": 3,
            "Thrower": 3,
            "Meteor Golem": 2,
            "Minion": 13,
            "Hog Rider": 14,
            "Valkyrie": 11,
            "Golem": 14,
            "Witch": 7,
            "Lava Hound": 7,
            "Bowler": 9,
            "Ice Golem": 9,
            "Headhunter": 3,
            "Apprentice Warden": 4,
            "Druid": 5,
            "Furnace": 4,
        },
        "spells": {
            "Lightning Spell": 12,
            "Healing Spell": 11,
            "Rage Spell": 6,
            "Poison Spell": 11,
            "Earthquake Spell": 7,
            "Jump Spell": 5,
            "Freeze Spell": 7,
            "Haste Spell": 6,
            "Skeleton Spell": 8,
            "Clone Spell": 8,
            "Bat Spell": 7,
            "Invisibility Spell": 4,
            "Overgrowth Spell": 4,
            "Recall Spell": 6,
            "Ice Block Spell": 5,
            "Revive Spell": 4,
            "Totem Spell": 2,
        },
        "siege_machines": {
            "Wall Wrecker": 5,
            "Battle Blimp": 5,
            "Stone Slammer": 5,
            "Siege Barracks": 5,
            "Log Launcher": 5,
            "Flame Flinger": 5,
            "Battle Drill": 5,
            "Troop Launcher": 4,
        },
        "offense_buildings": {
            "Army Camp": {"count": 4, "max_level": 13},
            "Barracks": {"count": 1, "max_level": 19},
            "Spell Factory": {"count": 1, "max_level": 9},
            "Dark Barracks": {"count": 1, "max_level": 12},
            "Dark Spell Factory": {"count": 1, "max_level": 7},
            "Workshop": {"count": 1, "max_level": 8},
            "Pet House": {"count": 1, "max_level": 12},
        },
        "defenses": {
            "Cannon": {"count": 0, "max_level": 21},
            "Archer Tower": {"count": 2, "max_level": 21},
            "Mortar": {"count": 4, "max_level": 17},
            "Air Defense": {"count": 4, "max_level": 15},
            "Wizard Tower": {"count": 5, "max_level": 17},
            "Air Sweeper": {"count": 2, "max_level": 7},
            "Hidden Tesla": {"count": 5, "max_level": 16},
            "Bomb Tower": {"count": 2, "max_level": 12},
            "X-Bow": {"count": 4, "max_level": 12},
            "Inferno Tower": {"count": 3, "max_level": 11},
            "Scattershot": {"count": 2, "max_level": 6},
            "Builder Hut": {"count": 5, "max_level": 7},
            "Monolith": {"count": 1, "max_level": 4},
            "Spell Tower": {"count": 2, "max_level": 4},
            "Multi-Archer Tower": {"count": 3, "max_level": 3},
            "Ricochet Cannon": {"count": 3, "max_level": 3},
            "Firespitter": {"count": 2, "max_level": 2},
            "Multi-Gear Tower": {"count": 1, "max_level": 2},
            "Inferno Artillery": {"count": 1, "max_level": 5},
        },
        "traps": {
            "Bomb": {"count": 8, "max_level": 13},
            "Spring Trap": {"count": 9, "max_level": 12},
            "Air Bomb": {"count": 7, "max_level": 12},
            "Giant Bomb": {"count": 8, "max_level": 11},
            "Seeking Air Mine": {"count": 9, "max_level": 7},
            "Skeleton Trap": {"count": 4, "max_level": 4},
            "Tornado Trap": {"count": 1, "max_level": 3},
            "Giga Bomb": {"count": 1, "max_level": 3},
        },
        "resource_buildings": {
            "Gold Mine": {"count": 7, "max_level": 17},
            "Elixir Collector": {"count": 7, "max_level": 17},
            "Gold Storage": {"count": 4, "max_level": 18},
            "Elixir Storage": {"count": 4, "max_level": 18},
            "Dark Elixir Drill": {"count": 3, "max_level": 11},
            "Dark Elixir Storage": {"count": 1, "max_level": 12},
            "Helper Hut": {"count": 1, "max_level": 1},
        },
        "army_buildings": {
            "Army Camp": {"count": 4, "max_level": 13},
            "Barracks": {"count": 1, "max_level": 19},
            "Clan Castle": {"count": 1, "max_level": 13},
            "Laboratory": {"count": 1, "max_level": 15},
            "Spell Factory": {"count": 1, "max_level": 9},
            "Hero Hall": {"count": 1, "max_level": 11},
            "Dark Barracks": {"count": 1, "max_level": 12},
            "Dark Spell Factory": {"count": 1, "max_level": 7},
            "Blacksmith": {"count": 1, "max_level": 9},
            "Workshop": {"count": 1, "max_level": 8},
            "Pet House": {"count": 1, "max_level": 12},
        },
        "core_buildings": {
            "Clan Castle": {"count": 1, "max_level": 13},
            "Laboratory": {"count": 1, "max_level": 15},
            "Hero Hall": {"count": 1, "max_level": 11},
            "Blacksmith": {"count": 1, "max_level": 9},
        },
        "walls": {"count": 325, "max_level": 18},
    },
    18: {
        "heroes": {
            "Barbarian King": 105,
            "Archer Queen": 105,
            "Minion Prince": 95,
            "Grand Warden": 80,
            "Royal Champion": 55,
            "Dragon Duke": 25,
        },
        "pets": {
            "L.A.S.S.I": 15,
            "Electro Owl": 15,
            "Mighty Yak": 15,
            "Unicorn": 15,
            "Frosty": 15,
            "Diggy": 10,
            "Poison Lizard": 15,
            "Phoenix": 10,
            "Spirit Fox": 10,
            "Angry Jelly": 10,
            "Sneezy": 10,
            "Greedy Raven": 10,
        },
        "troops": {
            "Barbarian": 12,
            "Archer": 14,
            "Giant": 14,
            "Goblin": 9,
            "Wall Breaker": 14,
            "Balloon": 12,
            "Wizard": 14,
            "Healer": 11,
            "Dragon": 12,
            "P.E.K.K.A": 13,
            "Baby Dragon": 12,
            "Miner": 12,
            "Electro Dragon": 9,
            "Yeti": 7,
            "Dragon Rider": 6,
            "Electro Titan": 5,
            "Root Rider": 3,
            "Thrower": 4,
            "Meteor Golem": 3,
            "Minion": 14,
            "Hog Rider": 15,
            "Valkyrie": 11,
            "Golem": 14,
            "Witch": 8,
            "Lava Hound": 8,
            "Bowler": 10,
            "Ice Golem": 9,
            "Headhunter": 3,
            "Apprentice Warden": 4,
            "Druid": 5,
            "Furnace": 4,
        },
        "spells": {
            "Lightning Spell": 13,
            "Healing Spell": 12,
            "Rage Spell": 6,
            "Poison Spell": 12,
            "Earthquake Spell": 8,
            "Jump Spell": 5,
            "Freeze Spell": 7,
            "Haste Spell": 7,
            "Skeleton Spell": 8,
            "Clone Spell": 8,
            "Bat Spell": 8,
            "Invisibility Spell": 4,
            "Overgrowth Spell": 4,
            "Recall Spell": 6,
            "Ice Block Spell": 5,
            "Revive Spell": 4,
            "Totem Spell": 2,
        },
        "siege_machines": {
            "Wall Wrecker": 6,
            "Battle Blimp": 5,
            "Stone Slammer": 6,
            "Siege Barracks": 5,
            "Log Launcher": 5,
            "Flame Flinger": 5,
            "Battle Drill": 5,
            "Troop Launcher": 4,
        },
        "offense_buildings": {
            "Army Camp": {"count": 4, "max_level": 13},
            "Barracks": {"count": 1, "max_level": 19},
            "Spell Factory": {"count": 1, "max_level": 9},
            "Dark Barracks": {"count": 1, "max_level": 12},
            "Dark Spell Factory": {"count": 1, "max_level": 7},
            "Workshop": {"count": 1, "max_level": 8},
            "Pet House": {"count": 1, "max_level": 12},
        },
        "defenses": {
            "Archer Tower": {"count": 2, "max_level": 21},
            "Mortar": {"count": 4, "max_level": 18},
            "Air Defense": {"count": 4, "max_level": 16},
            "Wizard Tower": {"count": 2, "max_level": 17},
            "Air Sweeper": {"count": 2, "max_level": 7},
            "Hidden Tesla": {"count": 5, "max_level": 17},
            "Bomb Tower": {"count": 2, "max_level": 13},
            "X-Bow": {"count": 4, "max_level": 12},
            "Inferno Tower": {"count": 3, "max_level": 12},
            "Scattershot": {"count": 2, "max_level": 6},
            "Builder Hut": {"count": 5, "max_level": 7},
            "Monolith": {"count": 1, "max_level": 4},
            "Spell Tower": {"count": 2, "max_level": 4},
            "Multi-Archer Tower": {"count": 3, "max_level": 4},
            "Ricochet Cannon": {"count": 3, "max_level": 4},
            "Firespitter": {"count": 2, "max_level": 3},
            "Multi-Gear Tower": {"count": 1, "max_level": 3},
            "Revenge Tower": {"count": 1, "max_level": 2},
            "Super Wizard Tower": {"count": 2, "max_level": 2},
        },
        "traps": {
            "Bomb": {"count": 8, "max_level": 13},
            "Spring Trap": {"count": 9, "max_level": 12},
            "Air Bomb": {"count": 7, "max_level": 13},
            "Giant Bomb": {"count": 8, "max_level": 11},
            "Seeking Air Mine": {"count": 9, "max_level": 7},
            "Skeleton Trap": {"count": 4, "max_level": 5},
            "Tornado Trap": {"count": 1, "max_level": 3},
            "Giga Bomb": {"count": 1, "max_level": 3},
        },
        "resource_buildings": {
            "Gold Mine": {"count": 7, "max_level": 17},
            "Elixir Collector": {"count": 7, "max_level": 17},
            "Gold Storage": {"count": 4, "max_level": 19},
            "Elixir Storage": {"count": 4, "max_level": 19},
            "Dark Elixir Drill": {"count": 3, "max_level": 11},
            "Dark Elixir Storage": {"count": 1, "max_level": 13},
            "Helper Hut": {"count": 1, "max_level": 1},
        },
        "army_buildings": {
            "Army Camp": {"count": 4, "max_level": 13},
            "Barracks": {"count": 1, "max_level": 19},
            "Clan Castle": {"count": 1, "max_level": 14},
            "Laboratory": {"count": 1, "max_level": 16},
            "Spell Factory": {"count": 1, "max_level": 9},
            "Hero Hall": {"count": 1, "max_level": 12},
            "Dark Barracks": {"count": 1, "max_level": 12},
            "Dark Spell Factory": {"count": 1, "max_level": 7},
            "Blacksmith": {"count": 1, "max_level": 9},
            "Workshop": {"count": 1, "max_level": 8},
            "Pet House": {"count": 1, "max_level": 12},
        },
        "core_buildings": {
            "Clan Castle": {"count": 1, "max_level": 14},
            "Laboratory": {"count": 1, "max_level": 16},
            "Hero Hall": {"count": 1, "max_level": 12},
            "Blacksmith": {"count": 1, "max_level": 9},
        },
        "walls": {"count": 325, "max_level": 19},
    },
}


def get_category_caps(th_level: int, category: str) -> dict:
    return TH_CAPS.get(th_level, {}).get(category, {})


def get_item_cap(th_level: int, category: str, item_name: str, default=None):
    return TH_CAPS.get(th_level, {}).get(category, {}).get(item_name, default)


def normalize_cap_entry(entry):
    if isinstance(entry, dict):
        return {
            "count": entry.get("count", 1),
            "max_level": entry.get("max_level", 0),
        }
    return {
        "count": 1,
        "max_level": int(entry or 0),
    }


def iter_th_cap_items(
    th_level: int, categories: list[str] | tuple[str, ...] | None = None
):
    caps = TH_CAPS.get(int(th_level), {}) or {}
    chosen_categories = categories or list(caps.keys())
    for category in chosen_categories:
        bucket = caps.get(category, {}) or {}
        if category == "walls":
            wall_count = int((bucket or {}).get("count", 0) or 0)
            wall_level = int((bucket or {}).get("max_level", 0) or 0)
            yield {
                "category": "walls",
                "item_name": "Wall",
                "count": wall_count,
                "max_level": wall_level,
                "entry": {"count": wall_count, "max_level": wall_level},
            }
            continue
        for item_name, raw in bucket.items():
            normalized = normalize_cap_entry(raw)
            yield {
                "category": category,
                "item_name": item_name,
                "count": int(normalized.get("count", 1) or 1),
                "max_level": int(normalized.get("max_level", 0) or 0),
                "entry": normalized,
            }


def get_all_cap_items(
    th_level: int, categories: list[str] | tuple[str, ...] | None = None
) -> list[dict]:
    return list(iter_th_cap_items(th_level, categories=categories))


def get_cap_total_slots(
    th_level: int, categories: list[str] | tuple[str, ...] | None = None
) -> int:
    return sum(
        int(item.get("count", 0) or 0)
        for item in iter_th_cap_items(th_level, categories=categories)
    )


CAP_CATEGORY_GROUPS = {
    # Advisor and war focus intentionally use offense + core buckets because those
    # buckets are the smaller, priority-oriented subset used by upgrade_advisor.
    "advisor_progress": (
        "heroes",
        "pets",
        "troops",
        "spells",
        "siege_machines",
        "offense_buildings",
        "core_buildings",
    ),
    # Full account completion must use the combined army_buildings bucket instead
    # of offense_buildings + core_buildings. army_buildings already contains both
    # sets, so including all three categories double-counts those structures.
    "account_completion": (
        "heroes",
        "pets",
        "troops",
        "spells",
        "siege_machines",
        "resource_buildings",
        "defenses",
        "traps",
        "army_buildings",
        "walls",
    ),
    "war_focus": (
        "heroes",
        "pets",
        "troops",
        "spells",
        "siege_machines",
        "offense_buildings",
        "core_buildings",
    ),
    # Farm focus also uses the combined army_buildings bucket to avoid counting
    # Army Camp, Laboratory, Clan Castle, etc. twice.
    "farm_focus": (
        "heroes",
        "pets",
        "resource_buildings",
        "army_buildings",
    ),
}


def get_cap_category_group(name: str) -> tuple[str, ...]:
    return tuple(CAP_CATEGORY_GROUPS.get(str(name or "").strip().lower(), ()))


def get_cap_total_slots_for_group(th_level: int, group_name: str) -> int:
    categories = get_cap_category_group(group_name)
    return get_cap_total_slots(th_level, categories=categories or None)
