from __future__ import annotations

# Account-completion-only items are modeled for TH-cap coverage and HTML rendering,
# but intentionally excluded from inferred advisor targets so they do not flood the
# recommendation engine or change the curated "top picks" behavior.
ACCOUNT_ONLY_CAP_NAME_MAP: dict[str, tuple[str, str]] = {
    "barbarian": ("troops", "Barbarian"),
    "archer": ("troops", "Archer"),
    "giant": ("troops", "Giant"),
    "goblin": ("troops", "Goblin"),
    "wall_breaker": ("troops", "Wall Breaker"),
    "wizard": ("troops", "Wizard"),
    "pekka": ("troops", "P.E.K.K.A"),
    "baby_dragon": ("troops", "Baby Dragon"),
    "yeti": ("troops", "Yeti"),
    "dragon_rider": ("troops", "Dragon Rider"),
    "electro_titan": ("troops", "Electro Titan"),
    "thrower": ("troops", "Thrower"),
    "meteor_golem": ("troops", "Meteor Golem"),
    "minion": ("troops", "Minion"),
    "valkyrie": ("troops", "Valkyrie"),
    "golem": ("troops", "Golem"),
    "witch": ("troops", "Witch"),
    "lava_hound": ("troops", "Lava Hound"),
    "bowler": ("troops", "Bowler"),
    "ice_golem": ("troops", "Ice Golem"),
    "headhunter": ("troops", "Headhunter"),
    "druid": ("troops", "Druid"),
    "furnace": ("troops", "Furnace"),
    "lightning_spell": ("spells", "Lightning Spell"),
    "healing_spell": ("spells", "Healing Spell"),
    "poison_spell": ("spells", "Poison Spell"),
    "earthquake_spell": ("spells", "Earthquake Spell"),
    "jump_spell": ("spells", "Jump Spell"),
    "haste_spell": ("spells", "Haste Spell"),
    "skeleton_spell": ("spells", "Skeleton Spell"),
    "clone_spell": ("spells", "Clone Spell"),
    "bat_spell": ("spells", "Bat Spell"),
    "overgrowth_spell": ("spells", "Overgrowth Spell"),
    "ice_block_spell": ("spells", "Ice Block Spell"),
    "revive_spell": ("spells", "Revive Spell"),
    "totem_spell": ("spells", "Totem Spell"),
    "barracks": ("offense_buildings", "Barracks"),
    "dark_barracks": ("offense_buildings", "Dark Barracks"),
    "dark_spell_factory": ("offense_buildings", "Dark Spell Factory"),
    "workshop": ("offense_buildings", "Workshop"),
    "archer_tower": ("defenses", "Archer Tower"),
    "mortar": ("defenses", "Mortar"),
    "wizard_tower": ("defenses", "Wizard Tower"),
    "builder_hut": ("defenses", "Builder Hut"),
    "dark_elixir_storage": ("resource_buildings", "Dark Elixir Storage"),
    "helper_hut": ("resource_buildings", "Helper Hut"),
    "wall": ("walls", "Wall"),
}


def apply_account_only_items(
    *,
    th_cap_name_map,
    min_copy_fallback_counts,
    items,
    item_meta,
    rebuild_th_cap_lookup,
):
    th_cap_name_map.update(ACCOUNT_ONLY_CAP_NAME_MAP)

    min_copy_fallback_counts.update({
        "archer_tower": 8,
        "mortar": 4,
        "wizard_tower": 5,
        "builder_hut": 5,
        "dark_elixir_storage": 1,
        "helper_hut": 1,
        "wall": 325,
    })

    items.update({
        "barbarian": item_meta("barbarian", "Barbarian", "troop", 4.0, 2.0, 0.0, 1.0, 2.0, lane="lab", source="troop"),
        "archer": item_meta("archer", "Archer", "troop", 4.0, 2.0, 0.0, 1.0, 2.0, lane="lab", source="troop"),
        "giant": item_meta("giant", "Giant", "troop", 4.2, 2.0, 0.0, 1.0, 2.1, lane="lab", source="troop"),
        "goblin": item_meta("goblin", "Goblin", "troop", 3.8, 3.5, 0.0, 1.0, 2.0, lane="lab", source="troop"),
        "wall_breaker": item_meta("wall_breaker", "Wall Breaker", "troop", 4.1, 1.5, 0.0, 1.0, 2.0, lane="lab", source="troop"),
        "wizard": item_meta("wizard", "Wizard", "troop", 4.6, 1.5, 0.0, 1.0, 2.2, lane="lab", source="troop"),
        "pekka": item_meta("pekka", "P.E.K.K.A", "troop", 5.0, 1.0, 0.0, 1.0, 2.4, lane="lab", source="troop"),
        "baby_dragon": item_meta("baby_dragon", "Baby Dragon", "troop", 4.8, 1.5, 0.0, 1.0, 2.3, lane="lab", source="troop"),
        "yeti": item_meta("yeti", "Yeti", "troop", 5.0, 1.0, 0.0, 1.0, 2.4, lane="lab", source="troop"),
        "dragon_rider": item_meta("dragon_rider", "Dragon Rider", "troop", 5.0, 1.0, 0.0, 1.0, 2.4, lane="lab", source="troop"),
        "electro_titan": item_meta("electro_titan", "Electro Titan", "troop", 5.2, 1.0, 0.0, 1.0, 2.5, lane="lab", source="troop"),
        "thrower": item_meta("thrower", "Thrower", "troop", 5.2, 1.0, 0.0, 1.0, 2.4, lane="lab", source="troop"),
        "meteor_golem": item_meta("meteor_golem", "Meteor Golem", "troop", 5.2, 1.0, 0.0, 1.0, 2.6, lane="lab", source="troop"),
        "minion": item_meta("minion", "Minion", "troop", 4.0, 2.0, 0.0, 1.0, 2.0, lane="lab", source="troop"),
        "valkyrie": item_meta("valkyrie", "Valkyrie", "troop", 4.6, 1.5, 0.0, 1.0, 2.2, lane="lab", source="troop"),
        "golem": item_meta("golem", "Golem", "troop", 4.8, 1.0, 0.0, 1.0, 2.3, lane="lab", source="troop"),
        "witch": item_meta("witch", "Witch", "troop", 4.7, 1.0, 0.0, 1.0, 2.2, lane="lab", source="troop"),
        "lava_hound": item_meta("lava_hound", "Lava Hound", "troop", 4.6, 1.0, 0.0, 1.0, 2.3, lane="lab", source="troop"),
        "bowler": item_meta("bowler", "Bowler", "troop", 4.7, 1.0, 0.0, 1.0, 2.2, lane="lab", source="troop"),
        "ice_golem": item_meta("ice_golem", "Ice Golem", "troop", 4.5, 1.0, 0.0, 1.0, 2.1, lane="lab", source="troop"),
        "headhunter": item_meta("headhunter", "Headhunter", "troop", 4.8, 1.0, 0.0, 1.0, 2.2, lane="lab", source="troop"),
        "druid": item_meta("druid", "Druid", "troop", 4.8, 1.0, 0.0, 1.0, 2.3, lane="lab", source="troop"),
        "furnace": item_meta("furnace", "Furnace", "troop", 4.8, 1.0, 0.0, 1.0, 2.3, lane="lab", source="troop"),
        "lightning_spell": item_meta("lightning_spell", "Lightning Spell", "spell", 4.5, 1.0, 0.0, 1.0, 2.0, lane="lab", source="spell"),
        "healing_spell": item_meta("healing_spell", "Healing Spell", "spell", 4.0, 1.0, 0.0, 1.0, 2.0, lane="lab", source="spell"),
        "poison_spell": item_meta("poison_spell", "Poison Spell", "spell", 4.0, 1.0, 0.0, 1.0, 2.0, lane="lab", source="spell"),
        "earthquake_spell": item_meta("earthquake_spell", "Earthquake Spell", "spell", 4.0, 1.0, 0.0, 1.0, 2.0, lane="lab", source="spell"),
        "jump_spell": item_meta("jump_spell", "Jump Spell", "spell", 3.8, 1.0, 0.0, 1.0, 1.8, lane="lab", source="spell"),
        "haste_spell": item_meta("haste_spell", "Haste Spell", "spell", 4.0, 1.0, 0.0, 1.0, 2.0, lane="lab", source="spell"),
        "skeleton_spell": item_meta("skeleton_spell", "Skeleton Spell", "spell", 3.8, 1.0, 0.0, 1.0, 1.9, lane="lab", source="spell"),
        "clone_spell": item_meta("clone_spell", "Clone Spell", "spell", 4.0, 1.0, 0.0, 1.0, 2.0, lane="lab", source="spell"),
        "bat_spell": item_meta("bat_spell", "Bat Spell", "spell", 3.8, 1.0, 0.0, 1.0, 1.9, lane="lab", source="spell"),
        "overgrowth_spell": item_meta("overgrowth_spell", "Overgrowth Spell", "spell", 4.0, 1.0, 0.0, 1.0, 2.0, lane="lab", source="spell"),
        "ice_block_spell": item_meta("ice_block_spell", "Ice Block Spell", "spell", 4.0, 1.0, 0.0, 1.0, 2.0, lane="lab", source="spell"),
        "revive_spell": item_meta("revive_spell", "Revive Spell", "spell", 4.0, 1.0, 0.0, 1.0, 2.0, lane="lab", source="spell"),
        "totem_spell": item_meta("totem_spell", "Totem Spell", "spell", 4.0, 1.0, 0.0, 1.0, 2.0, lane="lab", source="spell"),
        "barracks": item_meta("barracks", "Barracks", "building", 1.0, 0.5, 0.0, 1.0, 3.0, lane="builder"),
        "dark_barracks": item_meta("dark_barracks", "Dark Barracks", "building", 1.0, 0.5, 0.0, 1.0, 3.0, lane="builder"),
        "dark_spell_factory": item_meta("dark_spell_factory", "Dark Spell Factory", "building", 1.0, 0.5, 0.0, 1.0, 3.0, lane="builder"),
        "workshop": item_meta("workshop", "Workshop", "building", 1.5, 0.5, 0.0, 1.5, 3.0, lane="builder"),
        "archer_tower": item_meta("archer_tower", "Archer Tower", "defense", 0.0, 0.5, 4.5, 1.0, 2.5),
        "mortar": item_meta("mortar", "Mortar", "defense", 0.0, 0.5, 4.2, 1.0, 2.4),
        "wizard_tower": item_meta("wizard_tower", "Wizard Tower", "defense", 0.0, 0.5, 4.5, 1.0, 2.5),
        "builder_hut": item_meta("builder_hut", "Builder Hut", "defense", 0.0, 0.5, 4.0, 1.0, 2.4),
        "dark_elixir_storage": item_meta("dark_elixir_storage", "Dark Elixir Storage", "economy", 0.0, 3.0, 0.5, 1.0, 2.0),
        "helper_hut": item_meta("helper_hut", "Helper Hut", "economy", 0.0, 1.0, 0.0, 1.0, 1.0),
        "wall": item_meta("wall", "Wall", "building", 0.0, 0.0, 3.8, 0.5, 1.5, lane="builder"),
    })

    return set(ACCOUNT_ONLY_CAP_NAME_MAP.keys()), rebuild_th_cap_lookup()
