ACCOUNT_ONLY_AUTOSYNC_NAME_MAP = {
    "Barbarian": "barbarian",
    "Archer": "archer",
    "Giant": "giant",
    "Goblin": "goblin",
    "Wall Breaker": "wall_breaker",
    "Wizard": "wizard",
    "P.E.K.K.A": "pekka",
    "Baby Dragon": "baby_dragon",
    "Yeti": "yeti",
    "Dragon Rider": "dragon_rider",
    "Electro Titan": "electro_titan",
    "Thrower": "thrower",
    "Meteor Golem": "meteor_golem",
    "Minion": "minion",
    "Valkyrie": "valkyrie",
    "Golem": "golem",
    "Witch": "witch",
    "Lava Hound": "lava_hound",
    "Bowler": "bowler",
    "Ice Golem": "ice_golem",
    "Headhunter": "headhunter",
    "Druid": "druid",
    "Furnace": "furnace",
    "Lightning Spell": "lightning_spell",
    "Healing Spell": "healing_spell",
    "Poison Spell": "poison_spell",
    "Earthquake Spell": "earthquake_spell",
    "Jump Spell": "jump_spell",
    "Haste Spell": "haste_spell",
    "Skeleton Spell": "skeleton_spell",
    "Clone Spell": "clone_spell",
    "Bat Spell": "bat_spell",
    "Overgrowth Spell": "overgrowth_spell",
    "Ice Block Spell": "ice_block_spell",
    "Revive Spell": "revive_spell",
    "Totem Spell": "totem_spell",
}

AUTOSYNC_NAME_MAP = {
    # Heroes
    "Barbarian King": "barbarian_king",
    "Archer Queen": "archer_queen",
    "Grand Warden": "grand_warden",
    "Royal Champion": "royal_champion",
    "Minion Prince": "minion_prince",
    "Dragon Duke": "dragon_duke",
    # Troops
    "Healer": "healers",
    "Balloon": "balloons",
    "Dragon": "dragons",
    "Electro Dragon": "electro_dragon",
    "Hog Rider": "hog_rider",
    "Miner": "miners",
    "Root Rider": "root_rider",
    "Apprentice Warden": "apprentice_warden",
    # Spells
    "Rage Spell": "rage_spell",
    "Freeze Spell": "freeze_spell",
    "Invisibility Spell": "invisibility_spell",
    "Recall Spell": "recall_spell",
    # Pets
    "L.A.S.S.I": "lassi",
    "Lassi": "lassi",
    "Mighty Yak": "mighty_yak",
    "Electro Owl": "electro_owl",
    "Unicorn": "unicorn",
    "Phoenix": "phoenix",
    "Diggy": "diggy",
    "Poison Lizard": "poison_lizard",
    "Frosty": "frosty",
    "Spirit Fox": "spirit_fox",
    "Angry Jelly": "angry_jelly",
    "Sneezy": "sneezy",
    "Greedy Raven": "greedy_raven",
    # Siege machines
    "Wall Wrecker": "wall_wrecker",
    "Battle Blimp": "battle_blimp",
    "Stone Slammer": "stone_slammer",
    "Siege Barracks": "siege_barracks",
    "Log Launcher": "log_launcher",
    "Flame Flinger": "flame_flinger",
    "Battle Drill": "battle_drill",
    "Troop Launcher": "troop_launcher",
}
AUTOSYNC_NAME_MAP.update(ACCOUNT_ONLY_AUTOSYNC_NAME_MAP)