# Explicit asset filename mapping for Clash troop/spell/hero/siege icons.
# Values are asset stems under assets/icons/*.png. This keeps rendered cards
# from falling back to emoji when game/API keys are plural or use punctuation.
ITEM_ICON_ASSET_MAP: dict[str, str] = {
    # Heroes
    "barbarian_king": "barbarian_king",
    "archer_queen": "archer_queen",
    "grand_warden": "grand_warden",
    "royal_champion": "royal_champion",
    "minion_prince": "minion_prince",
    "dragon_duke": "dragon_duke",

    # Troops
    "barbarian": "barbarian",
    "archer": "archer",
    "giant": "giant",
    "goblin": "goblin",
    "wall_breaker": "wall_breaker",
    "balloon": "balloon",
    "balloons": "balloon",
    "wizard": "wizard",
    "healer": "healer",
    "healers": "healer",
    "dragon": "dragon",
    "dragons": "dragon",
    "pekka": "pekka",
    "p_e_k_k_a": "pekka",
    "baby_dragon": "baby_dragon",
    "miner": "miner",
    "miners": "miner",
    "electro_dragon": "electro_dragon",
    "yeti": "yeti",
    "dragon_rider": "dragon_rider",
    "electro_titan": "electro_titan",
    "root_rider": "root_rider",
    "thrower": "thrower",
    "meteor_golem": "meteor_golem",
    "apprentice_warden": "apprentice_warden",
    "druid": "druid",
    "furnace": "furnace",
    "minion": "minion",
    "hog_rider": "hog_rider",
    "valkyrie": "valkyrie",
    "golem": "golem",
    "witch": "witch",
    "lava_hound": "lava_hound",
    "bowler": "bowler",
    "ice_golem": "ice_golem",
    "headhunter": "headhunter",

    # Spells
    "lightning_spell": "lightning_spell",
    "healing_spell": "healing_spell",
    "rage_spell": "rage_spell",
    "poison_spell": "poison_spell",
    "earthquake_spell": "earthquake_spell",
    "jump_spell": "jump_spell",
    "freeze_spell": "freeze_spell",
    "haste_spell": "haste_spell",
    "skeleton_spell": "skeleton_spell",
    "clone_spell": "clone_spell",
    "bat_spell": "bat_spell",
    "invisibility_spell": "invisibility_spell",
    "overgrowth_spell": "overgrowth_spell",
    "recall_spell": "recall_spell",
    "ice_block_spell": "ice_block_spell",
    "revive_spell": "revive_spell",
    "totem_spell": "totem_spell",

    # Siege machines
    "wall_wrecker": "wall_wrecker",
    "battle_blimp": "battle_blimp",
    "stone_slammer": "stone_slammer",
    "siege_barracks": "siege_barracks",
    "log_launcher": "log_launcher",
    "flame_flinger": "flame_flinger",
    "battle_drill": "battle_drill",
    "troop_launcher": "troop_launcher",
}

ITEM_ICON_NAME_ALIASES: dict[str, str] = {
    "P.E.K.K.A": "pekka",
    "Wall Breaker": "wall_breaker",
    "Balloon": "balloon",
    "Balloons": "balloon",
    "Healer": "healer",
    "Healers": "healer",
    "Dragon": "dragon",
    "Dragons": "dragon",
    "Miner": "miner",
    "Miners": "miner",
    "Siege Barracks": "siege_barracks",
}