from __future__ import annotations

# Shop and loot-drop content are intentionally separate from bot_runner.py so the
# economy can grow without turning the runner into a giant config file.

SHOP_ITEMS = {
    "training_potion": {
        "name": "Training Potion",
        "cost": 450,
        "description": "Use /useitem training_potion to empower your next PvE or raid attack: +15% Gold, +15% Clan XP, and +10% Elixir.",
        "type": "combat_boost_charges",
        "charges": 1,
        "gold_multiplier": 1.15,
        "xp_multiplier": 1.15,
        "elixir_multiplier": 1.10,
        "required_th": 3,
    },
    "resource_potion": {
        "name": "Resource Potion",
        "cost": 400,
        "description": "Use /useitem resource_potion to empower your next farm run: +20% Gold, +20% Elixir, and a small chance at Dark Elixir.",
        "type": "farm_boost_charges",
        "charges": 1,
        "gold_multiplier": 1.20,
        "elixir_multiplier": 1.20,
        "dark_elixir_bonus_chance": 0.15,
        "required_th": 3,
    },
    "builder_potion": {
        "name": "Builder Potion",
        "cost": 1500,
        "description": "Use /useitem builder_potion to clear your Farm, Train, RaidVillage,RaidUser and BossAttack cooldowns once. Has a 30-minute use cooldown.",
        "type": "cooldown_clear",
        "use_cooldown_seconds": 1800,
        "required_th": 4,
    },
    "guard_shield": {
        "name": "Guard Shield",
        "cost": 500,
        "description": "Passive item. Automatically blocks the next successful /raiduser attack against your village, then breaks.",
        "type": "raiduser_defense",
        "required_th": 4,
    },
    "builder_crate": {
        "name": "Builder Crate",
        "cost": 600,
        "description": "Use /useitem builder_crate to gain bonus Gold and Clan XP toward Town Hall progression.",
        "type": "progression_bundle",
        "gold": 350,
        "clan_xp": 75,
        "required_th": 3,
    },
    "raid_medal_pack": {
        "name": "Raid Medal Pack",
        "cost": 700,
        "description": "Use /useitem raid_medal_pack to gain 10 Raid Medals.",
        "type": "raid_medals",
        "raid_medals": 10,
        "required_th": 5,
    },
    "hero_tome": {
        "name": "Hero Tome",
        "cost": 750,
        "description": "Use /useitem hero_tome to grant your active hero bonus XP.",
        "type": "hero_xp",
        "hero_xp": 100,
        "required_th": 4,
    },
    "dark_elixir_flask": {
        "name": "Dark Elixir Flask",
        "cost": 800,
        "description": "Use /useitem dark_elixir_flask to gain 100 Dark Elixir.",
        "type": "dark_elixir",
        "dark_elixir": 100,
        "required_th": 7,
    },
    "ore_pouch": {
        "name": "Ore Pouch",
        "cost": 900,
        "description": "Use /useitem ore_pouch to receive 3-7 Shiny Ore, with a small chance for 1 Glowy Ore.",
        "type": "ore_bundle",
        "shiny_ore_min": 3,
        "shiny_ore_max": 7,
        "glowy_ore_chance": 0.12,
        "glowy_ore_amount": 1,
        "required_th": 8,
    },
    "chest_key": {
        "name": "Chest Key",
        "cost": 1000,
        "description": "Use /useitem chest_key to receive one bonus chest roll.",
        "type": "chest_key",
        "required_th": 5,
    },
}

LOOT_DROP_STYLES = [
    {
        "name": "loot_crate",
        "weight": 50,
        "rewards": [100, 125],
        "spawn_messages": [
            "🛡️ **WAR SPOILS SECURED!**\n\nWar spoils secured from the battlefield. First Chief to type `claim` collects **{reward}** coins.",
            "🏆 **VICTORY LOOT!**\n\nVictory yields fresh spoils for the clan. Type `claim` to collect **{reward}** coins.",
            "🎁 **BATTLE REWARDS!**\n\nBattle rewards collected after the raid. First `claim` earns **{reward}** coins.",
            "🏚️ **FALLEN VILLAGE LOOT!**\n\nLoot recovered from the fallen village. Type `claim` before another Chief grabs **{reward}** coins.",
            "⚔️ **SUCCESSFUL ATTACK!**\n\nSpoils gathered from a successful attack. First `claim` takes **{reward}** coins.",
            "📦 **CLAN FORCES RETURN!**\n\nClan forces return with hard-earned loot. Type `claim` to secure **{reward}** coins.",
        ],
        "claim_messages": [
            "🛡️ {user} secured the battlefield spoils and collected **{reward}** coins!",
            "🏆 {user} claimed the victory loot and earned **{reward}** coins for the clan!",
            "🎁 {user} gathered the battle rewards and pocketed **{reward}** coins!",
            "🏚️ {user} recovered loot from the fallen village and gained **{reward}** coins!",
            "⚔️ {user} returned from a successful attack with **{reward}** coins!",
            "📦 {user} unloaded the clan forces' hard-earned loot for **{reward}** coins!",
        ],
    },
    {
        "name": "treasure_stash",
        "weight": 30,
        "rewards": [125, 150, 175],
        "spawn_messages": [
            "💰 **GOLD, ELIXIR & DARK ELIXIR!**\n\nGold, Elixir, and Dark Elixir secured. Type `claim` to convert the haul into **{reward}** coins.",
            "🏦 **ENEMY STORAGE RAIDED!**\n\nResources plundered from enemy storage. First `claim` banks **{reward}** coins.",
            "🪙 **GOLD & ELIXIR SEIZED!**\n\nGold and Elixir seized in battle. Type `claim` to collect **{reward}** coins.",
            "🛢️ **DARK ELIXIR RAID!**\n\nDark Elixir reserves successfully raided. First `claim` earns **{reward}** coins.",
            "📭 **STORAGES EMPTIED!**\n\nStorages emptied — loot collected. Type `claim` before the haul disappears for **{reward}** coins.",
            "🚚 **RESOURCE HAUL DELIVERED!**\n\nResource haul delivered to your clan. First `claim` receives **{reward}** coins.",
        ],
        "claim_messages": [
            "💰 {user} converted the Gold, Elixir, and Dark Elixir haul into **{reward}** coins!",
            "🏦 {user} emptied the enemy storages and banked **{reward}** coins!",
            "🪙 {user} seized the Gold and Elixir haul for **{reward}** coins!",
            "🛢️ {user} raided the Dark Elixir reserves and earned **{reward}** coins!",
            "📭 {user} swept the storages clean and collected **{reward}** coins!",
            "🚚 {user} delivered the resource haul and received **{reward}** coins!",
        ],
    },
    {
        "name": "war_spoils",
        "weight": 15,
        "rewards": [125, 150],
        "spawn_messages": [
            "💥 **DESTRUCTION COMPLETE!**\n\nDestruction complete — rewards claimed. First `claim` secures **{reward}** coins.",
            "⚔️ **ATTACK SUCCESSFUL!**\n\nAttack successful. War gains secured. Type `claim` to collect **{reward}** coins.",
            "🔥 **DEFENSES CRUSHED!**\n\nEnemy defenses crushed. Loot acquired. First `claim` takes **{reward}** coins.",
            "🎯 **RAID COMPLETE!**\n\nRaid complete. Rewards delivered. Type `claim` before another attacker grabs **{reward}** coins.",
            "🗡️ **STRIKE EXECUTED!**\n\nStrike executed. Resources captured. First `claim` earns **{reward}** coins.",
            "🏁 **VICTORY CONFIRMED!**\n\nVictory confirmed. War spoils collected. Type `claim` to claim **{reward}** coins.",
        ],
        "claim_messages": [
            "💥 {user} completed the destruction run and secured **{reward}** coins!",
            "⚔️ {user} locked in the successful attack and collected **{reward}** coins!",
            "🔥 {user} crushed the enemy defenses and acquired **{reward}** coins!",
            "🎯 {user} finished the raid and claimed **{reward}** coins!",
            "🗡️ {user} executed the strike and captured **{reward}** coins!",
            "🏁 {user} confirmed the victory and collected **{reward}** coins in war spoils!",
        ],
    },
    {
        "name": "jackpot",
        "weight": 5,
        "rewards": [200, 250, 300],
        "spawn_messages": [
            "🐉 **CLAN TREASURY REINFORCED!**\n\nClan treasury reinforced with new plunder. First `claim` collects **{reward}** coins.",
            "🏰 **WAR TRIBUTE DELIVERED!**\n\nWar tribute delivered to the clan. Type `claim` to receive **{reward}** coins.",
            "💪 **CLAN GROWS STRONGER!**\n\nThe clan grows stronger with each raid. First `claim` earns **{reward}** coins.",
            "📦 **CLAN RESERVES RESTOCKED!**\n\nPlunder added to the clan’s reserves. Type `claim` to collect **{reward}** coins.",
            "👑 **CHIEF'S ORDERS FULFILLED!**\n\nChief's orders fulfilled — loot secured. First `claim` takes **{reward}** coins.",
            "🏆 **RICHES RETURNED!**\n\nVictory brings riches back to the clan. Type `claim` to secure **{reward}** coins.",
        ],
        "claim_messages": [
            "🐉 {user} reinforced the clan treasury and collected **{reward}** coins!",
            "🏰 {user} accepted the war tribute and received **{reward}** coins!",
            "💪 {user} made the clan stronger and earned **{reward}** coins!",
            "📦 {user} restocked the clan reserves with **{reward}** coins!",
            "👑 {user} fulfilled the Chief's orders and secured **{reward}** coins!",
            "🏆 {user} brought riches back to the clan and claimed **{reward}** coins in war spoils!",
        ],
    },
]
